apiVersion: v1
kind: Service
metadata:
  name: paxos-web-service
spec:
  selector:
    app: paxos-web-service  # This should match the label in your deployment.yaml
  ports:
    - protocol: TCP
      port: 8080  # External port
      targetPort: 8080  # Port inside the container
  type: LoadBalancer  # Use NodePort or ClusterIP for internal access, LoadBalancer for external
